### ISSUE TITLE
Streams can't be defined

### ISSUE THREAD

**Issue by griseau** [unytics/airbyte_serverless#2]
When using it with the following config I have `TypeError: 'in <string>' requires string as left operand, not dict`

```
source:
  docker_image: "airbyte/source-github" # GENERATED | string | A Public Docker Airbyte Source. Example: `airbyte/source-faker:0.1.4`. (see connectors list at: "https://hub.docker.com/search?q=airbyte%2Fsource-" )
  config: # PREGENERATED | object | PLEASE UPDATE this pre-generated config by following the documentation https://docs.airbyte.com/integrations/sources/github
    credentials:
      personal_access_token: ${GITHUB_TOKEN} # SECRET (please store in environment variables) | REQUIRED | string | Log into GitHub and then generate a &lt;a href=&#34;https://github.com/settings/tokens&#34;&gt;personal access token&lt;/a&gt;. To load balance your API quota consumption across multiple API tokens, input multiple tokens separated with &#34;,&#34;
    repositories: 
      - "ORG/REPO"
    start_date: "2023-10-09T00:00:00Z" 
  streams: workflows_run
destination:
  connector: "print"
  config:
    buffer_size_max: 100
remote_runner:
  type: "cloud_run_job" # GENERATED | string | Runner Type. Must be one of ['direct', 'cloud_run_job']
  config: # PREGENERATED | object | PLEASE UPDATE this pre-generated config
    project:  # REQUIRED | string | GCP Project where cloud run job will be deployed
    region: "europe-west1" # REQUIRED | string | Region where cloud run job will be deployed
    service_account: "" # OPTIONAL | string | Service account email used bu Cloud Run Job. If empty default compute service account will be used

```

If you don't set streams it works, but requires to retrieve all data
